# Generated by Django 6.0.3 on 2026-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CIUDADANO', 'Ciudadano'), ('DEPENDENCIA', 'Dependencia'), ('DIRECCION', 'Direccion')], max_length=20)),
            ],
        ),
    ]
