# Generated by Django 6.0.3 on 2026-04-19 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_recepcion', models.CharField(blank=True, max_length=20, null=True)),
                ('folio_dependencia', models.CharField(blank=True, max_length=20, null=True)),
                ('folio_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('asunto', models.CharField(max_length=260)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
