# Generated by Django 6.0.3 on 2026-04-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='remitente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
